export type TestCase = {
  id: string;
  name: string;
  lengthType: "S" | "M" | "L";
  input: string;               // must end with space for conversion trigger
  expectedContains: string;     // positive: should contain | negative: should NOT contain
  type: "positive" | "negative" | "ui";
  delay?: number;              // typing delay in ms (human-like). long texts use smaller delay
};

export const testCases: TestCase[] = [
  // -------------------------
  // POSITIVE FUNCTIONAL (23) shamiq
  // -------------------------
  {
    id: "Pos_Fun_0001",
    name: "Greeting word - vanakkam",
    lengthType: "S",
    input: "vanakkam ",
    expectedContains: "வணக்கம்",
    type: "positive",
    delay: 70,
  },
  {
    id: "Pos_Fun_0002",
    name: "Thanks - nandri",
    lengthType: "S",
    input: "nandri ",
    expectedContains: "நன்றி",
    type: "positive",
    delay: 70,
  },
  {
    id: "Pos_Fun_0003",
    name: "Common phrase - eppadi irukkeenga",
    lengthType: "S",
    input: "eppadi irukkeenga? ",
    expectedContains: "எப்படி",
    type: "positive",
    delay: 65,
  },
  {
    id: "Pos_Fun_0004",
    name: "Polite request short",
    lengthType: "S",
    input: "konjam help pannunga ",
    expectedContains: "கொஞ்சம்",
    type: "positive",
    delay: 65,
  },
  {
    id: "Pos_Fun_0005",
    name: "Simple question with punctuation",
    lengthType: "S",
    input: "nee saptiya? ",
    expectedContains: "சாப்பிட்டியா",
    type: "positive",
    delay: 65,
  },
  {
    id: "Pos_Fun_0006",
    name: "Command - inge vaa",
    lengthType: "S",
    input: "inge vaa ",
    expectedContains: "இங்கே",
    type: "positive",
    delay: 70,
  },
  {
    id: "Pos_Fun_0007",
    name: "Apology word",
    lengthType: "S",
    input: "mannichidu ",
    expectedContains: "மன்னி",
    type: "positive",
    delay: 70,
  },
  {
    id: "Pos_Fun_0008",
    name: "Short emotional exclamation",
    lengthType: "S",
    input: "super! romba sandhosham! ",
    expectedContains: "சந்தோஷம்",
    type: "positive",
    delay: 55,
  },
  {
    id: "Pos_Fun_0009",
    name: "Present tense sentence",
    lengthType: "M",
    input: "naan innaiki college poren, class 10 manikku start aagum. ",
    expectedContains: "நான்",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0010",
    name: "Past tense sentence",
    lengthType: "M",
    input: "naan netru market poyirundhen; anga romba kootam irundhuchu. ",
    expectedContains: "நேற்று",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0011",
    name: "Future tense sentence",
    lengthType: "M",
    input: "naan naalai kalaila 7 manikku ezhundhu gym poguven. ",
    expectedContains: "நாளை",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0012",
    name: "Mixed English word - meeting",
    lengthType: "M",
    input: "innaiki meeting mudinjiduchu, aana next week follow up irukku. ",
    expectedContains: "முடிஞ்சிடுச்சு",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0013",
    name: "Mixed English word - bus/train",
    lengthType: "M",
    input: "bus late aachu, adhanala naan train pathi yosikkuren. ",
    expectedContains: "தாமதம்",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0014",
    name: "Numbers + time",
    lengthType: "M",
    input: "naan 2 hours wait pannen; ippo 3 manikku than reply vandhuchu. ",
    expectedContains: "மணிக்கு",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0015",
    name: "Date format included",
    lengthType: "M",
    input: "innaiki date 2026-01-30; exam hall ticket download panniten. ",
    expectedContains: "இன்று",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0016",
    name: "Multiple sentences + comma/semicolon",
    lengthType: "M",
    input: "nee vandha nalla irukkum, naanga ellarum wait panrom; seekram vaa. ",
    expectedContains: "சீக்கிரம்",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0017",
    name: "Health/food sentence",
    lengthType: "M",
    input: "naan innaiki saapadu light-aa dhaan saapten, athuku apram tea kudichen. ",
    expectedContains: "சாப்பாடு",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0018",
    name: "Travel sentence with place",
    lengthType: "M",
    input: "naan kalmunai la irukken; evening beach pakkam poga plan panren. ",
    expectedContains: "இருக்கேன்",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0019",
    name: "Question with polite tone",
    lengthType: "M",
    input: "please enakku konjam details sollunga, naan confuse aagiten. ",
    expectedContains: "தயவு",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0020",
    name: "Quotation marks + punctuation",
    lengthType: "M",
    input: 'naan "ok" nu sonnen, aana avanga ketkala. ',
    expectedContains: "சொன்னேன்",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0021",
    name: "Spelling variations + long word",
    lengthType: "M",
    input: "intha assignment romba important; correct-a submit pannanum. ",
    expectedContains: "அசைன்மெண்ட்",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0022",
    name: "Line break / paragraph style",
    lengthType: "M",
    input: "vanakkam\nnaan test cases ready panren.\nneenga check pannunga. ",
    expectedContains: "டெஸ்ட்",
    type: "positive",
    delay: 45,
  },
  {
    id: "Pos_Fun_0023",
    name: "Long paragraph (L) - human story",
    lengthType: "L",
    input:
      "vanakkam. naan innaiki ITPM assignment ku test cases design panren. first naan website open panni, input box la thanglish type panren. appo tamil auto convert aaguthu. aana sila words correct-a varala, athanala naan negative scenarios um add panren. ellam run panni report generate panni, excel la status update pannitu final submit panren. ",
    expectedContains: "அசைன்மெண்ட்",
    type: "positive",
    delay: 18,
  },
  {
  id: "Pos_Fun_0024",
  name: "Simple negation sentence",
  lengthType: "S",
  input: "naan innaiki varala ",
  expectedContains: "வரல",
  type: "positive",
  delay: 60,
},


  // -------------------------
  // NEGATIVE FUNCTIONAL (10)
  // These are robustness / invalid inputs.
  // Our automation expects NOT to contain the expectedContains phrase.
  // -------------------------
  {
    id: "Neg_Fun_0001",
    name: "Only symbols should not produce meaningful Tamil greeting",
    lengthType: "S",
    input: "@@@###$$$ ",
    expectedContains: "வணக்கம்",
    type: "negative",
    delay: 60,
  },
  {
    id: "Neg_Fun_0002",
    name: "Only numbers should not become a normal Tamil sentence",
    lengthType: "S",
    input: "1234567890 ",
    expectedContains: "நான்",
    type: "negative",
    delay: 60,
  },
  {
    id: "Neg_Fun_0003",
    name: "Emoji-only input",
    lengthType: "S",
    input: "😊😊😊 ",
    expectedContains: "நன்றி",
    type: "negative",
    delay: 60,
  },
  {
    id: "Neg_Fun_0004",
    name: "Weird mixed special chars with letters",
    lengthType: "S",
    input: "v@n@kk@m ",
    expectedContains: "வணக்கம்",
    type: "negative",
    delay: 60,
  },
  {
    id: "Neg_Fun_0005",
    name: "No vowel / incomplete fragments",
    lengthType: "S",
    input: "vnnkkm ",
    expectedContains: "வணக்கம்",
    type: "negative",
    delay: 60,
  },
  {
    id: "Neg_Fun_0006",
    name: "Repeated characters (nonsense stretch)",
    lengthType: "M",
    input: "vanakkkkkkkkkkkkkkkkkammmmmmmmmmmmmmm ",
    expectedContains: "வணக்கம்",
    type: "negative",
    delay: 35,
  },
  {
    id: "Neg_Fun_0007",
    name: "Random keyboard mash",
    lengthType: "M",
    input: "asdjkl qweuiop zxcvbnm poiuytrew ",
    expectedContains: "சந்தோஷம்",
    type: "negative",
    delay: 35,
  },
  {
    id: "Neg_Fun_0008",
    name: "English sentence only (should not exactly match Tamil expected phrase)",
    lengthType: "M",
    input: "this is only english text for testing purpose ",
    expectedContains: "இன்று",
    type: "negative",
    delay: 35,
  },
  {
    id: "Neg_Fun_0009",
    name: "Only punctuation",
    lengthType: "S",
    input: "!!! ??? ... ,, ;; ",
    expectedContains: "நான்",
    type: "negative",
    delay: 60,
  },
  {
    id: "Neg_Fun_0010",
    name: "Very long nonsense (L) - repeated pattern",
    lengthType: "L",
    input:
      "aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa aaaaa ",
    expectedContains: "அசைன்மெண்ட்",
    type: "negative",
    delay: 12,
  },

  // -------------------------
  // UI TEST (1)  -> total cases = 34
  // -------------------------
  {
    id: "Pos_UI_0001",
    name: "UI: Text converts after typing and space",
    lengthType: "S",
    input: "vanakkam ",
    expectedContains: "வணக்கம்",
    type: "ui",
    delay: 70,
  },
];
